[theme]
base = "light"
primaryColor = "#6366f1"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f4f8"
textColor = "#1b1e27"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
